Monitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitoring/', include('planning_approvals.urls')),
    path('monitoring/accounts/', include('django.contrib.auth.urls')),

]

planning_approvals/urls.py
from django.urls import path
from . import views
from planning_approvals.views import SiteCreate, SiteUpdate, SiteDelete, PlanningAppUpdate, PlanningAppDelete, PlotCreate, NoteCreate, PlanningAppCreate


urlpatterns = [
    path('', views.index, name='index'),
    path('sites/', views.SiteListView.as_view(), name='sites'),
    path('site/<int:pk>', views.SiteDetailView.as_view(), name='site-detail'),
    path('planningapps/', views.Planning_AppListView.as_view(), name='planningapps'),
    path('planningapp/<int:pk>', views.Planning_AppDetailView.as_view(), name='planningapp-detail'),
    path('trajectory/', views.TrajectoryListView.as_view(), name='trajectory'),
    path('site/add/', SiteCreate.as_view(), name='site_create'),
    path('site/<int:pk>/edit/', SiteUpdate.as_view(), name='site_update'),
    path('site/<int:pk>/delete/', SiteDelete.as_view(), name='site_delete'),
    path('planningapp/add/', PlanningAppCreate.as_view(), name='planningapp_create'),
    path('planningapp/<int:pk>/edit/', PlanningAppUpdate.as_view(), name='planningapp_update'),
    path('planningapp/<int:pk>/delete/', PlanningAppDelete.as_view(), name='planningapp_delete'),
    path('planningapp/<int:pk>/addplots/', PlotCreate.as_view(), name='plot_create'),
    path('planningapp/<int:pk>/add-notes/', NoteCreate.as_view(), name='note_create'),
]

planning_approvals/models.py
from django.db import models
from django.db.models import Count, Q
from django.contrib.auth.models import User
from django.urls import reverse
import datetime

class Parish(models.Model):
    parish = models.CharField(max_length=20, blank=True, null=True)
    settlement = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
         """String for representing the model object (in Admin site etc.)."""
         return self.parish
        
    class Meta:
        verbose_name_plural='Parishes'
  

class Site(models.Model):
    """Model for site which serves groups planning apps and allocations"""

    # Fields
    site_ref = models.CharField(max_length=20, help_text='Reference for site')
    site_name = models.CharField(max_length=80)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)    

    # Metadata
    class Meta: 
        ordering = ['site_ref']

    def get_absolute_url(self):
        return reverse('site-detail', args=[str(self.id)])
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return self.site_ref

    
    
class PlanningApp(models.Model):
    app_ref = models.CharField(max_length=20, help_text='Unique reference code for planning application or site allocation', verbose_name="Application reference")
    policy = models.CharField(max_length=20, blank=True, null=True, help_text='Local Plan policy reference')
    superseded_by_app = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, help_text='Reference no. of application which supersedes this record')
    superseded_date = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True, help_text='Date this record was superseded (e.g. date new app granted permission)')
    site = models.ForeignKey(Site, on_delete=models.CASCADE, help_text='Site to which approval relates')
    address = models.TextField(help_text='Street address for application site')
    parish = models.ForeignKey(Parish, on_delete=models.CASCADE, blank=True, null=True, help_text='Civil parish in which approval is located')
    proposal = models.TextField(verbose_name="Description of development proposal")
    
    APP_TYPE_CHOICES = (
        ('a', 'Allocation'),
        ('f', 'Full Planning'),
        ('o', 'Outline'),
        ('pn', 'Prior Notification'),
        ('pip', 'Permission in Priciple'),
        ('rm', 'Reserved Matters'),
        )
    
    app_type = models.CharField(
        max_length=5,
        choices=APP_TYPE_CHOICES,
        blank=True,
        null=True,
        verbose_name='Approval type',
        help_text='Type of approval or permission',
    )
    
    decision_date = models.DateField(blank=True, null=True, auto_now=False, auto_now_add=False, help_text='Date permission granted')
    appeal_decision_date = models.DateField(blank=True, null=True, auto_now=False, auto_now_add=False, help_text='Date appeal decision issued')
    committee_decision_date = models.DateField(blank=True, null=True, auto_now=False, auto_now_add=False, help_text='Date of planning committee decision')
    lapse_date = models.DateField(blank=True, null=True, auto_now=False, auto_now_add=False, help_text='Date permission lapses')
    
    DEV_TYPE_CHOICES = (
        ('new', 'New Building(s)'),
        ('cou', 'Change of Use'),
        ('rebld', 'Rebuild Applications'),
        ('conv', 'Conversion of a dwellings'),
        ('dem', 'Demolition of floorspace'),
        )
    
    dev_type = models.CharField(
        max_length=5,
        choices=DEV_TYPE_CHOICES,
        blank=True,
        null=True,
        verbose_name='Development type',
        help_text='Type of development e.g. new build, change of use, etc.',
    )
    
        
    DEV_CLASS_CHOICES = (
        ('inf', 'Infill 1-2 dwellings'),
        ('grp', 'Group 3-8 dwellings'),
        ('est', 'Estate 9+ dwellings'),
        ('cou', 'Residential Change of Use'),
        ('con', 'Residential conversion'),
        ('dem', 'Demolition of a dwelling'),
        ('prk', 'Park Homes development'),
        ('rep', 'Replacement dwelling'),        
        )
    
    dev_class = models.CharField(
        max_length=5,
        choices=DEV_CLASS_CHOICES,
        blank=True,
        null=True, 
        help_text='Development class',
    )
    
    PDL_CHOICES = (
        ('g', 'Greenfield'),
        ('b', 'Brownfield'),
        ('m', 'Mix of Greenfield and Brownfield'),
        )
    
    pdl = models.CharField(
        max_length=1,
        choices=PDL_CHOICES,
        blank=True,
        null=True,
        verbose_name='PDL',
        help_text='Previously developed land i.e. Greenfield / Brownfield land',
    )
    
    site_capacity = models.IntegerField(default=0, blank=True, null=True, help_text='Total no. of dwellings permitted')
    units_lost = models.IntegerField(default=0, blank=True, null=True, help_text='No. of dwellings lost through development of site')
    
    lapsed = models.BooleanField(default=False, help_text='Where permission not implemented before lapse date, manually set application to \'lapsed\' status')
    not_applicable = models.BooleanField(default=False, help_text='Omit site from monitoring data, without deleting record')
    
    current_status = models.CharField(max_length=30, default="Extant", blank=True, null=True, help_text='(Auto) Defines current status of planning permission')
    
    #trajectory
    year_01 = models.IntegerField(default=0, blank=True, null=True)
    year_02 = models.IntegerField(default=0, blank=True, null=True)
    year_03 = models.IntegerField(default=0, blank=True, null=True)
    year_04 = models.IntegerField(default=0, blank=True, null=True)
    year_05 = models.IntegerField(default=0, blank=True, null=True)
    year_06 = models.IntegerField(default=0, blank=True, null=True)
    year_07 = models.IntegerField(default=0, blank=True, null=True)
    year_08 = models.IntegerField(default=0, blank=True, null=True)
    year_09 = models.IntegerField(default=0, blank=True, null=True)
    year_10 = models.IntegerField(default=0, blank=True, null=True)
    year_11 = models.IntegerField(default=0, blank=True, null=True)
    year_12 = models.IntegerField(default=0, blank=True, null=True)
    year_13 = models.IntegerField(default=0, blank=True, null=True)
    year_14 = models.IntegerField(default=0, blank=True, null=True)
    year_15 = models.IntegerField(default=0, blank=True, null=True)
    year_16 = models.IntegerField(default=0, blank=True, null=True)
    year_17 = models.IntegerField(default=0, blank=True, null=True)
    year_18 = models.IntegerField(default=0, blank=True, null=True)
    year_19 = models.IntegerField(default=0, blank=True, null=True)
    year_20 = models.IntegerField(default=0, blank=True, null=True)
    
    traj_comments = models.TextField(blank=True, null=True)
    traj_internal_notes = models.TextField(blank=True, null=True)
    
    
    DELIVERABLE_CHOICES = (
        ('A', 'a) Site is not major development'),
        ('B', 'b) Site with detailed planning permission'),
        ('C', 'c) Site with outline planning permission with clear evidence that housing completions will begin on site within five years'),
        ('D', 'd) Site with permission in principle with clear evidence that housing completions will begin on site within five years'),
        ('E', 'e) Site allocated within the development plan with clear evidence that housing completions will begin on site within five years'),
        ('F', 'f) Site identified on a brownfield register with clear evidence that housing completions will begin on site within five years'),
        ('G', 'g) Site without consent but with clear evidence that housing completions will begin on site within five years'),
        ('H', 'h) Site is not considered deliverable within five years or there is insufficient evidence site will be delivered within five years'),
        )
    
    deliverable = models.CharField(
        max_length=1,
        choices=DELIVERABLE_CHOICES,
        blank=True,
        null=True, 
        help_text='How permission meets deliverable definition in national policy',
    )
    
    # additional applications and planning history
    additional_app = models.TextField(blank=True, null=True, help_text='Relevant details of additional applications (e.g. new applications pending determination)')
    planning_history = models.TextField(blank=True, null=True, help_text='Details of previous applications on site')
    application_docs_url = models.URLField(max_length=255, blank=True, null=True, help_text='Link to online planning application documents')
    
    # map / location info
    site_plan_url = models.URLField(max_length=255, blank=True, null=True, help_text='Link to site plan')
    easting = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    northing = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    site_area = models.DecimalField(max_digits=6, decimal_places=2, default=0, blank=True, null=True)
    
 
    # log of created / updated date
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True) 
    

    # @property calcs
    @property
    def net_gain(self):
        return self.site_capacity - self.units_lost
    
    @property
    def five_year_total(self):
        return (
            self.year_01 +
            self.year_02 +
            self.year_03 +
            self.year_04 +
            self.year_05
            )
    
    @property
    def trajectory_total(self):
        return (
            self.year_01 +
            self.year_02 +
            self.year_03 +
            self.year_04 +
            self.year_05 +
            self.year_06 +
            self.year_07 +
            self.year_08 +
            self.year_09 +

planning_approvals/forms.py
from .models import PlanningApp, Site, Plot, Parish, Note
from django.contrib.auth.models import User
from django import forms
from .widgets import FengyuanChenDatePickerInput
from django.conf import settings



class PlanningAppForm(forms.ModelForm):
    class Meta:
        model = PlanningApp
        fields = '__all__'
        widgets = {
            'address': forms.Textarea(attrs={'cols': 30, 'rows': 3}),
            'proposal': forms.Textarea(attrs={'cols': 30, 'rows': 5}),
            'decision_date': FengyuanChenDatePickerInput(attrs={'autocomplete': 'off'}),
            'appeal_decision_date': FengyuanChenDatePickerInput(attrs={'autocomplete': 'off'}),
            'committee_decision_date': FengyuanChenDatePickerInput(attrs={'autocomplete': 'off'}),
            'lapse_date': FengyuanChenDatePickerInput(attrs={'autocomplete': 'off'}),
            'superseded_date': FengyuanChenDatePickerInput(attrs={'autocomplete': 'off'}),
            'site_capacity': forms.NumberInput(attrs={'class':'form-number'}),
            'units_lost': forms.NumberInput(attrs={'class':'form-number'}),
            }
        
    def __init__(self, *args, **kwargs):
        super(PlanningAppForm, self).__init__(*args, **kwargs)
        self.fields['decision_date'].input_formats=(settings.DATE_INPUT_FORMATS)
        self.fields['appeal_decision_date'].input_formats=(settings.DATE_INPUT_FORMATS)
        self.fields['committee_decision_date'].input_formats=(settings.DATE_INPUT_FORMATS)
        self.fields['lapse_date'].input_formats=(settings.DATE_INPUT_FORMATS)
        self.fields['superseded_date'].input_formats=(settings.DATE_INPUT_FORMATS)
# class PlotForm(forms.ModelForm):
#     class Meta:
#         model = Plot
#         fields = '__all__'

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = '__all__'




# class PlanningAppForm(forms.Form):
#     class Meta:
#         template_name = 'planning_approvals/create_planningapp_detail.html'
#         model = PlanningApp
#         fields = [
#             'app_ref',
#             'policy',
#             'superseded_by_app',
#             'superseded_date',
#             'site',
#             'address',
#             'parish',
#             'proposal',
#             'app_type',
#             'decision_date',
#             'appeal_decision_date',
#             'committee_decision_date',
#             'lapse_date',
#             'dev_type',
#             'dev_class',
#             'pdl',
#             'site_capacity',
#             'units_lost',
#             'lapsed',
#             'not_applicable',
#             'current_status',
#             'year_01',
#             'year_02',
#             'year_03',
#             'year_04',
#             'year_05',
#             'year_06',
#             'year_07',
#             'year_08',
#             'year_09',
#             'year_10',
#             'year_11',
#             'year_12',
#             'year_13',
#             'year_14',
#             'year_15',
#             'year_16',
#             'year_17',
#             'year_18',
#             'year_19',
#             'year_20',
#             'traj_comments',
#             'traj_internal_notes',
#             'deliverable',
#             'planning_history',
#             'additional_app',
#             'application_docs_url',
#             'site_plan_url',
#             'easting',
#             'northing',
#             'site_area',
#             'author',
#             
#             
#             ]
            
        

planning_approvals/templates/planning_approvals/add_note.html
{% extends "base_generic.html" %}
    {% load crispy_forms_tags %}
{% block content %}

<form action="" method="post">
	{% csrf_token %}
	{{ formset|crispy }}
	{{ formset.errors }}
	
	<button type="submit" class="btn btn-primary">Submit</button>
</form>



{% endblock %}

planning_approvals/templates/planning_approvals/add_plot.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
	{% csrf_token %}
	{{ formset.as_table }}
	{{ formset.errors }}
	
	<button type="submit" class="btn btn-primary">Submit</button>
</form>



{% endblock %}

planning_approvals/templates/planning_approvals/planningapp_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<div class="card border-primary mb-3">
  <div class="card-header">Delete Planning Approval</div>
  <div class="card-body">
   
    <p class="card-text">
Are you sure you want to delete planning app <strong>{{ planningapp }}</strong> ?

<form action="" method="POST">
  {% csrf_token %}
  
  <button type="submit" class="btn btn-primary">Yes, delete</button>

</form>

{% endblock %}

</p>
  </div>
</div>

planning_approvals/templates/planning_approvals/planningapp_list.html
{% extends "base_generic.html" %}


{% block content %}
  <h1>Planning Approvals</h1>
  <div class="row mt-3"></div>
  <a href="{% url 'planningapp_create' %}"  class="btn btn-primary" role="button">Add new</a>
  <a href="/monitoring/planningapp/add"  class="btn btn-primary" role="button">Upload csv</a>
  <div class="row mt-3"></div>
  {% if planningapp_list %}
  
  <div>
  <table class="table table-hover sortable">
  <thead>
    <tr>
      <th scope="col">App ref</th>
      <th scope="col">Site</th>
      <th scope="col">Address</th>
      <th scope="col">Parish</th>
      <th scope="col">Granted</th>
      <th scope="col">Appeal</th>
      <th scope="col">Current status</th>
    </tr>
  </thead>
  <tbody>
    {% for app in planningapp_list %}
    <tr>
      <td><a href="{{ app.get_absolute_url }}">{{ app.app_ref }}</a></td>
      <td><a href="{{ app.get_site_url }}">{{ app.site }}</a></td>
      <td>{{ app.address }}</td>
      <td>{{ app.parish }}</td>
      <td>{{ app.decision_date }}</td>
      <td>{{ app.appeal_decision_date }}</td>
      <td>{{ app.current_status }}</td>
    </tr>

    {% endfor %}
</tbody>
</table>

  {% else %}
    <p>There are no planning approvals in the database.</p>
  {% endif %}       
{% endblock %}
</div>

planning_approvals/templates/planning_approvals/site_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<div class="card border-primary mb-3">
  <div class="card-header">Delete site</div>
  <div class="card-body">
   
    <p class="card-text">
Are you sure you want to delete site <strong>{{ site }}</strong> ?

<form action="" method="POST">
  {% csrf_token %}
  
  <button type="submit" class="btn btn-primary">Yes, delete</button>

</form>

{% endblock %}

</p>
  </div>
</div>

planning_approvals/templates/planning_approvals/site_detail.html
{% extends "base_generic.html" %}

{% block content %}


<div class="card border-primary mb-3">
  <div class="card-header">Site Details</div>
  <div class="card-body">
    <h4 class="card-title">Site Ref: {{ site.site_ref }}</h4>
    <p class="card-text">
      <div>
      <strong>Site name:</strong> {{ site.site_name }}<br /><br />
      <strong>Created:</strong> {{ site.created_on }} | <strong>Last updated:</strong> {{ site.updated_on }}<br /><br />
  
  
    <a href="/monitoring/site/{{ site.id }}/edit" class="btn btn-primary" role="button">Edit</button></a>
    <a href="{ % url 'site_delete' % }" class="btn btn-primary" role="button">Delete</button></a>
    
    </p>
   </div>
   </div>
  </div>
  
<div class="row mt-3"></div>

<div>
<h4>Planning Approvals for site {{ site.site_ref }}</h4>
</div>
{% for app in site.planningapp_set.all %}
<div class="row mt-3"></div>

<div class="card border-secondary mb-3">
  <div class="card-header"><h4><a href={{ app.get_absolute_url }}>{{app.app_ref }} - {{ app.address }}</a></h4>
  </div>
  
   
  <div class="card-body">
    <h4 class="card-title">{{ app.proposal}}</h4>
    <p class="card-text">{{ app.current_status }}</p>
      
  </div>
</div>
  
    {% endfor %}
  
<div>
<a href="{% url 'sites' %}" class="btn btn-primary" role="button" style="float: right;">Back</button></a>
</div>

<div class="row mt-3"></div>
{% endblock %}

planning_approvals/templates/planning_approvals/site_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="card border-primary mb-3">
  <div class="card-header">Add / edit site</div>
  <div class="card-body">
    
    <p class="card-text">
  <form action="" method="post">
    {% csrf_token %}
	{{ form | crispy }}
	<button type="submit" class="btn btn-primary">Save</button>
  </form>
  </p>
  </div>
</div>
{% endblock %}

planning_approvals/templates/planning_approvals/site_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Sites</h1>
  <a href="/monitoring/site/add/"  class="btn btn-primary" role="button">Add site</a>
  <div class="row mt-3"></div>
  {% if site_list %}

<div>
  <table class="table table-hover sortable">
  <thead>
    <tr>
      <th scope="col">Site ref</th>
      <th scope="col">Site name</th>
      <th scope="col">Last updated</th>
    </tr>
  </thead>
  <tbody>
    {% for site in site_list %}
    <tr>
      <td><a href="{{ site.get_absolute_url }}">{{ site.site_ref }}</a></td>
      <td>{{site.site_name}}</td>
      <td>{{site.updated_on}}</td>
    </tr>

    {% endfor %}
</tbody>
</table>


  {% else %}
    <p>There are no sites in the database.</p>
  {% endif %}       
{% endblock %}


</div>

planning_approvals/templates/planning_approvals/traj_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Housing trajectory</h1>
  {% if planningapp_list %}
 
 <div> 
  <table class="table table-hover sortable">
      <thead>  
    <tr>
    <th>Site Ref</th>
    <th>App Ref</th> 
    <th>Address</th>
    <th>Policy</th>
    <th>Address</th>
    <th>Parish</th>
    <th>Application type</th>
    <th>Decision date</th>
    <th>Appeal date</th>
    <th>Proposal</th>
    <th>Site capacity</th>
    <th>Plots demolished</th>
    <th>Plots completed</th>
    <th>Plots commenced</th>
    <th>Net commitment</th>
    <th>Yr 1</th>
    <th>Yr 2</th>
    <th>Yr 3</th>
    <th>Yr 4</th>
    <th>Yr 5</th>
    <th>Five year total</th>
  </tr>
  </thead>
  
  <tbody>
  
    {% for app in planningapp_list %}
    
    <tr>
    <td><a href="{{ app.get_site_url }}">{{ app.site }}</a></td>
    <td><a href="{{ app.get_absolute_url }}">{{ app.app_ref }}</a></td> 
    <td>{{ app.address }}</td>
    <td>{{ app.policy|default_if_none:""}}</td>
    <td>{{ app.address }}</td>
    <td>{{ app.parish }}</td>
    <td>{{ app.get_app_type_display }}</td>
    <td>{{ app.decision_date|default_if_none:"" }}</td>
    <td>{{ app.appeal_decision_date|default_if_none:"" }}</td>
    <td>{{ app.proposal }}</td>
    <td>{{ app.site_capacity }}</td>
    <td>{{ app.plots_completed }}</td>
    <td>{{ app.plots_commenced }}</td>
    <td>{{ app.net_commitment }}</td>
    <td>{{ app.year_01 }}</td>
    <td>{{ app.year_02 }}</td>
    <td>{{ app.year_03 }}</td>
    <td>{{ app.year_04 }}</td>
    <td>{{ app.year_05 }}</td>
    <td>{{ app.five_year_total }}</td>

  </tr>
  {% endfor %}
  </tbody>
  </table>
       
      
    
 
  {% else %}
    <p>There are no planning approvals in the database.</p>
  {% endif %}
  </div>       
{% endblock %}